### ISSUE TITLE
reis

### ISSUE THREAD

**Issue by witchfindertr** [Berkanktk/BeReal-Fetcher#1]
hedef profilin dataları getir miyor dimi o yok mu ?

**Comment by Berkanktk** [comment]
> hedef profilin dataları getir miyor dimi o yok mu ?

JSON data olarak getiriyor. 

**Bunlarin icinde hedefin:**
- Paylastigi fotograflari
- Lokasyonu (long/lat)
- Baskalarin yaptigi reaksyon ve yorumlarini gösteriyor
