### ISSUE TITLE
Add support for memories

### ISSUE THREAD

**Issue by ishan0102** [Berkanktk/BeReal-Fetcher#2]
Hi, thank you so much for making this, it's very well written! I'd been searching for soemthing like this for a while and yours was the best one I've found. I noticed there was an endpoint not covered by your script: `https://mobile.bereal.com/api/feeds/memories`. I was wondering if you were willing to add support for this? I would love to download all of my memories. Thank you!

**Comment by Berkanktk** [comment]
You actually only need to change the endpoint at line 70 from this:

`response = requests.get('https://mobile.bereal.com/api/feeds/friends', headers=headers, params=params, verify=False)`

to this

`response = requests.get('https://mobile.bereal.com/api/feeds/memories', headers=headers, params=params, verify=False)`

And it will work perfectly fine :)

**Comment by ishan0102** [comment]
Amazing, thank you!

**Comment by ishan0102** [comment]
@Berkanktk Sorry to bother you, but do you have the `SECURE_TOKEN` value or is it different for each user? If so, could you send it to me by chance, I kind of want to avoid paying for Charles Proxy 😅

**Comment by Berkanktk** [comment]
Sorry for the late answer, I didn’t have time to reply earlier. The `SECURE_TOKEN` is not private, but since Github wouldn’t be happy about me posting some sort of token, i'll just send it to your E-mail! 💯

**Comment by ishan0102** [comment]
Got it, thank you so much :) Starred the repo as well!
